/*
 * An include file to define common attributes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines AccountType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountType
    {
        /// <summary>
        /// Enum CACC for value: CACC
        /// </summary>
        [EnumMember(Value = "CACC")]
        CACC = 1,

        /// <summary>
        /// Enum CASH for value: CASH
        /// </summary>
        [EnumMember(Value = "CASH")]
        CASH = 2,

        /// <summary>
        /// Enum CHAR for value: CHAR
        /// </summary>
        [EnumMember(Value = "CHAR")]
        CHAR = 3,

        /// <summary>
        /// Enum CISH for value: CISH
        /// </summary>
        [EnumMember(Value = "CISH")]
        CISH = 4,

        /// <summary>
        /// Enum COMM for value: COMM
        /// </summary>
        [EnumMember(Value = "COMM")]
        COMM = 5,

        /// <summary>
        /// Enum CPAC for value: CPAC
        /// </summary>
        [EnumMember(Value = "CPAC")]
        CPAC = 6,

        /// <summary>
        /// Enum LLSV for value: LLSV
        /// </summary>
        [EnumMember(Value = "LLSV")]
        LLSV = 7,

        /// <summary>
        /// Enum LOAN for value: LOAN
        /// </summary>
        [EnumMember(Value = "LOAN")]
        LOAN = 8,

        /// <summary>
        /// Enum MGLD for value: MGLD
        /// </summary>
        [EnumMember(Value = "MGLD")]
        MGLD = 9,

        /// <summary>
        /// Enum MOMA for value: MOMA
        /// </summary>
        [EnumMember(Value = "MOMA")]
        MOMA = 10,

        /// <summary>
        /// Enum NREX for value: NREX
        /// </summary>
        [EnumMember(Value = "NREX")]
        NREX = 11,

        /// <summary>
        /// Enum ODFT for value: ODFT
        /// </summary>
        [EnumMember(Value = "ODFT")]
        ODFT = 12,

        /// <summary>
        /// Enum ONDP for value: ONDP
        /// </summary>
        [EnumMember(Value = "ONDP")]
        ONDP = 13,

        /// <summary>
        /// Enum OTHR for value: OTHR
        /// </summary>
        [EnumMember(Value = "OTHR")]
        OTHR = 14,

        /// <summary>
        /// Enum SACC for value: SACC
        /// </summary>
        [EnumMember(Value = "SACC")]
        SACC = 15,

        /// <summary>
        /// Enum SLRY for value: SLRY
        /// </summary>
        [EnumMember(Value = "SLRY")]
        SLRY = 16,

        /// <summary>
        /// Enum SVGS for value: SVGS
        /// </summary>
        [EnumMember(Value = "SVGS")]
        SVGS = 17,

        /// <summary>
        /// Enum TAXE for value: TAXE
        /// </summary>
        [EnumMember(Value = "TAXE")]
        TAXE = 18,

        /// <summary>
        /// Enum TRAN for value: TRAN
        /// </summary>
        [EnumMember(Value = "TRAN")]
        TRAN = 19,

        /// <summary>
        /// Enum TRAS for value: TRAS
        /// </summary>
        [EnumMember(Value = "TRAS")]
        TRAS = 20

    }

}
