/*
 * An include file to define common attributes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BankProfileResponse
    /// </summary>
    [DataContract(Name = "bankProfileResponse")]
    public partial class BankProfileResponse : IEquatable<BankProfileResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankProfileResponse" /> class.
        /// </summary>
        /// <param name="bankProfileDescriptor">bankProfileDescriptor.</param>
        public BankProfileResponse(BankProfileDescriptor bankProfileDescriptor = default(BankProfileDescriptor))
        {
            this.BankProfileDescriptor = bankProfileDescriptor;
        }

        /// <summary>
        /// Gets or Sets BankProfileDescriptor
        /// </summary>
        [DataMember(Name = "bankProfileDescriptor", EmitDefaultValue = false)]
        public BankProfileDescriptor BankProfileDescriptor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BankProfileResponse {\n");
            sb.Append("  BankProfileDescriptor: ").Append(BankProfileDescriptor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BankProfileResponse);
        }

        /// <summary>
        /// Returns true if BankProfileResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of BankProfileResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankProfileResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BankProfileDescriptor == input.BankProfileDescriptor ||
                    (this.BankProfileDescriptor != null &&
                    this.BankProfileDescriptor.Equals(input.BankProfileDescriptor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BankProfileDescriptor != null)
                    hashCode = hashCode * 59 + this.BankProfileDescriptor.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
