/*
 * An include file to define common attributes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Consent authorization denied descriptor
    /// </summary>
    [DataContract(Name = "DenyRequest")]
    public partial class DenyRequest : IEquatable<DenyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DenyRequest" /> class.
        /// </summary>
        /// <param name="consentAuth">consentAuth.</param>
        /// <param name="backToFinTech">Will indicate if PSU wants to be sent back to FinTechApi..</param>
        /// <param name="exitPage">In case there is no redirect back to TPP desired, exit page can be specified by ConsentAuthorisationApi.</param>
        /// <param name="forgetConsent">Set to true if consent object shall be forgotten or frozen..</param>
        public DenyRequest(ConsentAuth consentAuth = default(ConsentAuth), bool backToFinTech = default(bool), string exitPage = default(string), bool forgetConsent = default(bool))
        {
            this.ConsentAuth = consentAuth;
            this.BackToFinTech = backToFinTech;
            this.ExitPage = exitPage;
            this.ForgetConsent = forgetConsent;
        }

        /// <summary>
        /// Gets or Sets ConsentAuth
        /// </summary>
        [DataMember(Name = "consentAuth", EmitDefaultValue = false)]
        public ConsentAuth ConsentAuth { get; set; }

        /// <summary>
        /// Will indicate if PSU wants to be sent back to FinTechApi.
        /// </summary>
        /// <value>Will indicate if PSU wants to be sent back to FinTechApi.</value>
        [DataMember(Name = "backToFinTech", EmitDefaultValue = true)]
        public bool BackToFinTech { get; set; }

        /// <summary>
        /// In case there is no redirect back to TPP desired, exit page can be specified by ConsentAuthorisationApi
        /// </summary>
        /// <value>In case there is no redirect back to TPP desired, exit page can be specified by ConsentAuthorisationApi</value>
        [DataMember(Name = "exitPage", EmitDefaultValue = false)]
        public string ExitPage { get; set; }

        /// <summary>
        /// Set to true if consent object shall be forgotten or frozen.
        /// </summary>
        /// <value>Set to true if consent object shall be forgotten or frozen.</value>
        [DataMember(Name = "forgetConsent", EmitDefaultValue = true)]
        public bool ForgetConsent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DenyRequest {\n");
            sb.Append("  ConsentAuth: ").Append(ConsentAuth).Append("\n");
            sb.Append("  BackToFinTech: ").Append(BackToFinTech).Append("\n");
            sb.Append("  ExitPage: ").Append(ExitPage).Append("\n");
            sb.Append("  ForgetConsent: ").Append(ForgetConsent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DenyRequest);
        }

        /// <summary>
        /// Returns true if DenyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DenyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DenyRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConsentAuth == input.ConsentAuth ||
                    (this.ConsentAuth != null &&
                    this.ConsentAuth.Equals(input.ConsentAuth))
                ) && 
                (
                    this.BackToFinTech == input.BackToFinTech ||
                    this.BackToFinTech.Equals(input.BackToFinTech)
                ) && 
                (
                    this.ExitPage == input.ExitPage ||
                    (this.ExitPage != null &&
                    this.ExitPage.Equals(input.ExitPage))
                ) && 
                (
                    this.ForgetConsent == input.ForgetConsent ||
                    this.ForgetConsent.Equals(input.ForgetConsent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConsentAuth != null)
                    hashCode = hashCode * 59 + this.ConsentAuth.GetHashCode();
                hashCode = hashCode * 59 + this.BackToFinTech.GetHashCode();
                if (this.ExitPage != null)
                    hashCode = hashCode * 59 + this.ExitPage.GetHashCode();
                hashCode = hashCode * 59 + this.ForgetConsent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
